package qz.bigdata.crawler.store.mysql;

import org.apache.commons.dbcp.BasicDataSourceFactory;

import javax.sql.DataSource;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.Properties;


public class MysqlClient {
	
	private static DataSource ds;

	static{
		try {
			Properties prop = new Properties();
			InputStream is = MysqlClient.class.getResourceAsStream("/dbcp.properties");
			prop.load(is);
			BasicDataSourceFactory factory = new BasicDataSourceFactory(); 
			ds = factory.createDataSource(prop);

		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	public static Connection getConnection() throws ClassNotFoundException,SQLException{
		Connection conn = ds.getConnection();
		if(conn != null){
			System.out.println("创建mysql连接成功！");
		}
		return conn;
	}
//
//	public static Statement createStatement(Connection conn) {
//		Statement stmt = null;
//		try {
//			stmt = conn.createStatement();
//		} catch (SQLException e) {
//			e.printStackTrace();
//		}
//		return stmt;
//	}
//
//	public static ResultSet executeQuery(Statement stmt, String sql) {
//		ResultSet rs = null;
//		try {
//			rs = stmt.executeQuery(sql);
//		} catch (SQLException e) {
//			e.printStackTrace();
//		}
//		return rs;
//	}
//
//	public static int executeUpdate(Connection conn, String sql) {
//		int row = 0;
//		Statement stmt = null;
//		try {
//			stmt = conn.createStatement();
//			row = stmt.executeUpdate(sql);
//		} catch (SQLException e) {
//			e.printStackTrace();
//		} finally {
//			close(stmt);
//		}
//		return row;
//	}
//
//	public static PreparedStatement prepareStatement(Connection conn, String sql) {
//		PreparedStatement pstmt = null;
//		try {
//			pstmt = conn.prepareStatement(sql);
//		} catch (SQLException e) {
//			e.printStackTrace();
//		}
//		return pstmt;
//	}
//
//	public static PreparedStatement prepareStatement(Connection conn,
//		String sql, int autoGeneratedKeys) {
//		PreparedStatement pstmt = null;
//		try {
//			pstmt = conn.prepareStatement(sql, autoGeneratedKeys);
//		} catch (SQLException e) {
//			e.printStackTrace();
//		}
//		return pstmt;
//	}
//
//	public static void close(PreparedStatement pstmt) {//����ʹ��close(Statement stmt)����,��������ָ���������;
//		if (null != pstmt) {
//			try {
//				pstmt.close();
//			} catch (SQLException e) {
//				e.printStackTrace();
//			}
//		}
//		pstmt = null;
//	}

	
}
